language: cpp
git:
  submodules: false

stages:
  - name: Build example

jobs:
  - &build-on-windows
    stage: Build example
    name: Visual Studio 2019
    os: windows
    script:
      - bash -c '"C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Auxiliary/Build/vcvarsall.bat" x64'
      - cmake -G"NMake Makefiles" .
      - nmake
